### ISSUE TITLE
i couldn't make it work

### ISSUE THREAD

**Issue by xlith** [artemvd/webform_crosspage_conditions#1]
Hi,
i installed this addon on my D8 site but couldn't make it work.

**Comment by artemvd** [comment]
Hi, did you have any errors on installation? Webform module was updated and maybe some classes are a bit out of date. What version of Drupal and Webform you are using?

**Comment by artemvd** [comment]
Did you also set the conditions in webform UI for the fields? This addon only converts the already existing state rules to crosspage conditions, it doesn't provide any UI for this.

**Comment by xlith** [comment]
Hi,
i am using 
Drupal 8.3.5 
Webform 8.x-5.0-beta15+69-dev (2017-Jul-31) 

let me try new version i will tell you the results in a bit.

**Comment by artemvd** [comment]
If possible, please provide some logs with errors from php log, or recent log messages from Drupal.

**Comment by xlith** [comment]
sorry for late return. 
i record a screencast for you. 
https://youtu.be/ZQ1Qh3U0_k4

hope this helps.

**Comment by artemvd** [comment]
Hi, thank you for the screencast. The problem is that my addon is a webfrom Handler. It is not applied to all webforms by default. If you want to apply the crosspage conditions check to your given webform you need after setting up all the elements to navigate to "Emails/Handlers" tab of your form and click on "Add handler" and select "Webform crosspage conditions" and add it to the form.
Hope this would help. I will update the documentation to make it more clear.

**Comment by xlith** [comment]
Hi, i am sorry i took your time. so i was wrong to apply the handler. 
But when i did it the right way. server returns http 500 error. here is the error log:

2017/08/02 07:57:34 [error] 11475#11475: *1389 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Class 'Drupal\webform\WebformHandlerBase' not found in /var/www/html/tubimertest/modules/webform_crosspage_conditions/src/Plugin/WebformHandler/WebformCrosspageConditionsHandler.php on line 21" while reading response header from upstream, client: ***.**.***.***, server: tubimertest.**.com, request: "POST /admin/structure/webform/manage/deneme_webform/handlers/add/multipage_conditional_fields?_wrapper_format=drupal_modal HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "tubimertest.**.com", referrer: "http://tubimertest.**.com/admin/structure/webform/manage/deneme_webform/handlers"

**Comment by artemvd** [comment]
Thank you for review of the error. I will check, I think that Webform changed API a bit and I have written the handler a year ago. I will check and make it up to date. I will write the result here and update the codebase.

**Comment by artemvd** [comment]
Now it should work, the path to the class of WebformHandlerBase was changed in webform module. Please clone the latest code and it will be working.

Thanks for your feedback and help to make the addon better.
